### ISSUE TITLE
Resolution issues

### ISSUE THREAD

**Issue by filikun** [N-l1/lovelace-soft-ui#7]
Hey, awesome style! I have a problem with resolutions though. My GF have a Samsung Galaxy S10e with a smaller display and you can see for yourself that the buttons get cropped. Is there any way around this? I'm no expert in with styling so I'm not sure what I can do.

https://imgur.com/a/T0Vixpr

**Comment by N-l1** [comment]
Thank you! I am aware of this problem and it is something I am planning to improve. However, I’m quite busy at the moment so don’t expect it too soon. 

The simplest solution is to remove the fifth card.

It has been also mentioned [on the forums](https://community.home-assistant.io/t/lovelace-soft-ui-simple-and-clean-lovelace-configuration/159357/63)

**Comment by KTibow** [comment]
Thanks for the fix! I've noticed on bigger displays, it isn't centered in the middle though too. Thanks for all of your work in Soft UI!
[![The buttons are aligned to the left...](https://user-images.githubusercontent.com/10727862/82160474-8388bd80-984a-11ea-91b5-139de89ccd13.png)](#)

**Comment by N-l1** [comment]
Okay @KTibow, thanks for letting me know! 👍

**Comment by KTibow** [comment]
Would this work if you used percentages instead of pixels?

**Comment by N-l1** [comment]
Yes! Don't know why I didn't think of that. Would you like to do some testing @KTibow?

**Comment by KTibow** [comment]
I can try that out. I'm worried that it might not end up being square, though.  
If the width is `10%` of the **width of the bigger** horizontal arrangement, the height needs to be `10%` of the **width of the bigger** horizontal arrangement, not `10%` of the **height of the bigger** horizontal arrangement.

**Comment by N-l1** [comment]
Yes, good point. Check [this](https://www.w3schools.com/howto/howto_css_aspect_ratio.asp) out.

**Comment by KTibow** [comment]
Okay, (note to self and anybody else) here's a slightly changed for simplicity example entry (with `px`).
<details><summary>This is basically the plain YAML minus some stuff</summary>

```yaml
cards:
# First card
 -  icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Second card
 -  icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Third card
 -  icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                             
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fourth card
 -  icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fifth card
 -  icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;              
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
type: horizontal-stack
```
</details>

**Comment by KTibow** [comment]
@N-l1 they look **way** too tiny in width. <details><summary>(Code here, any ideas?)</summary>

```yaml
cards:
  - icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                             
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;              
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
type: horizontal-stack
```
</details>

**Comment by N-l1** [comment]
Interesting... I was thinking of doing something with [relative lengths](https://www.w3schools.com/cssref/css_units.asp).

**Comment by KTibow** [comment]
Hmm. What I have so far now (WIP):
<details><summary>Hidden for convenience by default</summary>

```yaml
cards:
  - icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - position: relative
        - height: 60px
        - padding-top: 50%
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - position: absolute
        - top: 0
        - right: 0
        - bottom: 0
        - left: 0
    type: 'custom:button-card'
  - icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                             
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;              
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
type: horizontal-stack
```

**Comment by N-l1** [comment]
Some promising results using this code. Seems to work on a smaller phone I tested! 🎉  
<details><summary>Show code</summary>

```yaml
cards:
# First card
 -  icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Second card
 -  icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Third card
 -  icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fourth card
 -  icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fifth card
 -  icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
type: horizontal-stack
```
</details>

**Comment by KTibow** [comment]
@N-l1 fantastic! I'll start working on increasing the margin on larger screens.

**Comment by KTibow** [comment]
@N-l1 I've done that. I've also added extra left padding, so it aligns better. Next step is adding back the more specific stuff, like the shadowing.
<details><summary>What do you think?</summary>

```yaml
cards:
  - icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        margin-left: 6.5px;
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px; 
           margin-left: 4px;
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
      @media only screen and (min-width: 1200px) {
         ha-card {
           margin: 8px;  
           margin-left: 11px;
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
  - icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
      @media only screen and (min-width: 1200px) {
         ha-card {
           margin: 8px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
  - icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
      @media only screen and (min-width: 1200px) {
         ha-card {
           margin: 8px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
  - icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
      @media only screen and (min-width: 1200px) {
         ha-card {
           margin: 8px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
  - icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
      @media only screen and (min-width: 1200px) {
         ha-card {
           margin: 8px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
type: horizontal-stack
```
</details>
(You can do the PR this time 😄)

**Comment by N-l1** [comment]
Wonderful! Updating the code...

**Comment by N-l1** [comment]
Issue resolved as part of commit 1aee410!

**Comment by N-l1** [comment]
Just realized I changed the code for the wrong card 🤦‍♂️

Has been fixed now...

**Comment by filikun** [comment]
Nice work but I still have a problem. The whole bar does not seem to center.  Here is how it looks for me now. The two first "button bars" are the old way and the 3rd is the new code. 


![signal-attachment-2020-05-20-191858](https://user-images.githubusercontent.com/9947929/82476883-f4400c00-9ace-11ea-9acf-675c6d5ce2b2.jpeg)

**Comment by KTibow** [comment]
@filikun in order to solve this, customize the Media Queries:
```
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px; 
           margin-left: 4px;                   
         }
      }
      @media only screen and (min-width: 1200px) {
         ha-card {
           margin: 8px;  
           margin-left: 11px;               
         }
      }
```
Modify the **max-width: 600px** and the **min-width: 1200px** and the **margin-left: 4px;** and the **margin-left: 11px;**

**Comment by Harry-1976** [comment]
> @filikun in order to solve this, customize the Media Queries:
> 
> ```
>       @media only screen and (max-width: 600px) {
>          ha-card {
>            margin: 3px; 
>            margin-left: 4px;                   
>          }
>       }
>       @media only screen and (min-width: 1200px) {
>          ha-card {
>            margin: 8px;  
>            margin-left: 11px;               
>          }
>       }
> ```
> 
> Modify the **max-width: 600px** and the **min-width: 1200px** to change the thresholds.
> Modify the **margin-left: 4px;** and the **margin-left: 11px;** to change the margin on the left.

Looking at the screen shot i think @filikun may even remove both @media sections. The standard styling already fits perfectly.

**Comment by KTibow** [comment]
@Harry-1976 but then if it's landscape, or on a giant display it might not work.

**Comment by Harry-1976** [comment]
@KTibow True that. Your mod works for me.

**Comment by N-l1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub Repository ✨](https://trello.com/c/PO3MyOZ2/4-github-repository-%E2%9C%A8)

**Comment by KTibow** [comment]
@N-l1 it says it's private, did you just invite Harry-1976 or filikun?

**Comment by N-l1** [comment]
I am sorry. I had no intension of posting a link, probably accidentally clicked something.
